name: Build

on:
  push:
    branches: ['*']
  pull_request:

concurrency:                         # cancel older runs on the same ref
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, 24]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js and cache node_modules
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install deps
        run: npm ci --prefer-offline --no-audit

      - name: Lint
        run: npm run lint

      - name: Type-check
        run: npm run check-types

      - name: Build app
        run: npm run build

      - name: Lint
        run: yarn lint
        if: always()

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist